version: '3.8'
services:
  dev-db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nest
    networks:
      - freecodecamp
    volumes:
      - auth-prisma-data:/var/lib/mysql

networks:
  freecodecamp:
    external: true

volumes:
  auth-prisma-data: 
      