version: '3.8'
services:
  dev-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nest
      MYSQL_USER: gabebott
      MYSQL_PASSWORD: 123
    networks:
      - freecodecamp
networks:
  freecodecamp: